server.port=8080

# Database Configuration (Supabase PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.zzxkpeegvmbbnxbfehnx.supabase.co:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=yPSlQeDRgQ8TnnOE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false

# JPA/Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail Configuration (Mock/Default properties. Application will fallback gracefully to logging if invalid)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.test-connection=false

# JPA config
spring.jpa.open-in-view=false

# Custom JWT Configuration
# 256-bit Hex Key (64 characters)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
